export const ColourType = {
    red: 'bg-red-700',
    orange: 'bg-orange-700',
    amber: 'bg-amber-700',
    yellow: 'bg-yellow-700',
    lime: 'bg-lime-700',
    green: 'bg-green-700',
    emerald: 'bg-emerald-700',
    teal: 'bg-teal-700',
    cyan: 'bg-cyan-700',
    sky: 'bg-sky-700',
    blue: 'bg-blue-700',
    indigo: 'bg-indigo-700',
    violet: 'bg-violet-700',
    purple: 'bg-purple-700',
    fuchsia: 'bg-fuchsia-700',
    pink: 'bg-pink-700',
    rose: 'bg-rose-700',
    slate: 'bg-slate-700',
    gray: 'bg-gray-700',
    zinc: 'bg-zinc-700',
    neutral: 'bg-neutral-700',
    stone: 'bg-stone-700',
    taupe: 'bg-taupe-700',
    mauve: 'bg-mauve-700',
    mist: 'bg-mist-700',
    olive: 'bg-olive-700',
} as const

export type ColourType = (typeof ColourType)[keyof typeof ColourType]
